# Generated by Django 5.0.7 on 2024-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("product_logo", models.ImageField(upload_to="Product_logo/")),
                ("stock_status", models.BooleanField()),
                ("product_price", models.IntegerField()),
            ],
        ),
    ]
