# Generated by Django 5.0.7 on 2024-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="account_type",
            field=models.JSONField(default=list),
        ),
    ]
