# Generated by Django 5.0.7 on 2024-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0004_product_validity_in_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_logo",
            field=models.FileField(upload_to="Product_logo/"),
        ),
    ]
