# Generated by Django 5.0.7 on 2024-07-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0006_customusermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="full_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
