# Generated by Django 5.0.7 on 2024-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0007_customusermodel_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
