# Generated by Django 4.2.14 on 2024-07-26 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0008_alter_customusermodel_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusermodel",
            options={"permissions": []},
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="last_name",
        ),
    ]
